config/routes.rb
Rails.application.routes.draw do

  get 'home/index'

  resources :jokes do
    collection do
      get 'daily_joke'
    end
  end

   root 'home#index'

end

app/models/joke.rb
class Joke < ActiveRecord::Base
	def self.daily_joke(options)
		if options.nil?
			joke_ids = self.ids
			joke = self.find(joke_ids.sample)
		else
			array = options.split(",")
			joke_ids = self.where('id NOT IN (?)',array).ids
		 	joke = joke_ids.blank? ? nil : self.find(joke_ids.sample)
		end
		joke
	end
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/jokes_controller.rb
class JokesController < ApplicationController
  before_action :set_joke, only: [:show, :edit, :update, :destroy]

  def daily_joke
    joke = Joke.daily_joke(cookies[:da])
    if cookies[:da].nil?
      cookies[:da] = "#{joke.id}"
    else
      cookies[:da] +=  ",#{joke.id}" unless joke.blank?
    end
    result = I18n.t 'message'
    result = joke.joke_content unless joke.blank?
    render json: {message: result}, status: :ok
  end
  # GET /jokes
  # GET /jokes.json
  def index
    @jokes = Joke.all
  end

  # GET /jokes/1
  # GET /jokes/1.json
  def show
  end

  # GET /jokes/new
  def new
    @joke = Joke.new
  end

  # GET /jokes/1/edit
  def edit
  end

  # POST /jokes
  # POST /jokes.json
  def create
    @joke = Joke.new(joke_params)

    respond_to do |format|
      if @joke.save
        format.html { redirect_to @joke, notice: 'Joke was successfully created.' }
        format.json { render :show, status: :created, location: @joke }
      else
        format.html { render :new }
        format.json { render json: @joke.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jokes/1
  # PATCH/PUT /jokes/1.json
  def update
    respond_to do |format|
      if @joke.update(joke_params)
        format.html { redirect_to @joke, notice: 'Joke was successfully updated.' }
        format.json { render :show, status: :ok, location: @joke }
      else
        format.html { render :edit }
        format.json { render json: @joke.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jokes/1
  # DELETE /jokes/1.json
  def destroy
    @joke.destroy
    respond_to do |format|
      format.html { redirect_to jokes_url, notice: 'Joke was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_joke
      @joke = Joke.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def joke_params
      params.require(:joke).permit(:joke_content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/joke_dbs_helper.rb
module JokeDbsHelper
end

app/helpers/jokes_helper.rb
module JokesHelper
end

app/views/home/index.html.erb
 <%= javascript_include_tag 'home' %>
 <%= stylesheet_link_tag    'home' %>
<div class="container-fluid">
	<div class="jumbotron text-center">
		<h2>A joke a day keeps the doctor away</h2>
		<small>If you joke wrong way, your teeth have to pay. (serious)</small>
	</div>
	<div class="col-sm-6 col-sm-offset-3">
		<p id="joke_content">joke</p>
	</div>
	<div class="col-sm-6 col-sm-offset-3 text-center btn-action">
		<button type="button" class="btn btn-vote btn-like" id="btn-like">This is funny!</button>
		<button type="button" class="btn btn-vote btn-dislike" id="btn-dislike">This is not funny</button>
	</div>
</div>

app/views/jokes/_form.html.erb
<%= form_for(@joke) do |f| %>
  <% if @joke.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@joke.errors.count, "error") %> prohibited this joke from being saved:</h2>

      <ul>
      <% @joke.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :joke_content %><br>
    <%= f.text_area :joke_content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<script>
  $(function() {
      $('#joke_joke_content').froalaEditor()
  });
</script>

app/views/jokes/edit.html.erb
<h1>Editing Joke</h1>

<%= render 'form' %>

<%= link_to 'Show', @joke %> |
<%= link_to 'Back', jokes_path %>

app/views/jokes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Jokes</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jokes.each do |joke| %>
      <tr>
        <td><%= joke.joke_content.html_safe %></td>
        <td><%= link_to 'Show', joke %></td>
        <td><%= link_to 'Edit', edit_joke_path(joke) %></td>
        <td><%= link_to 'Destroy', joke, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Joke', new_joke_path %>

app/views/jokes/new.html.erb
<h1>New Joke</h1>

<%= render 'form' %>

<%= link_to 'Back', jokes_path %>

app/views/jokes/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Joke content:</strong>
  <%= raw(@joke.joke_content) %>
</p>
<%= link_to 'Edit', edit_joke_path(@joke) %> |
<%= link_to 'Back', jokes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FurtureworkzTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js' %>
  <%= csrf_meta_tags %>
</head>
	<body>
	<nav class="navbar navbar-default">
	  <div class="container">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="#">FutureWorkz Test</a>
	    </div>
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav navbar-right">
	        <li><a href="#">Le Sy Thang</a></li>
	      </ul>
	    </div>
	  </div>
	</nav>
	<%= yield %>

	</body>
	<footer class="footer">
		<div class="container text-center">
			<p>This website use Ruby on Rails, Bootstrap 3</p>
			<p>Copyright 2015 - Le Sy Thang</p>
		</div>
	</footer>
</html>